$color = rgba(13, 13, 13, 1)
$inner_color = rgba(13, 13, 13, 0.66)
$outer_color = rgba(238, 141, 129, 1)
$font_color = rgba(235, 235, 235, 1)
$placeholder_color = rgba(235, 235, 235, 0.7)
$check_color = rgba(255, 211, 98, 1)
