background            #0D0D0D
foreground            #EBEBEB

# black
color0  #0D0D0D
color8  #68665f

# red
color1  #c58468
color9  #e69471

# green
color2  #efb770
color10 #ffc969

# yellow
color3  #ffdf91
color11 #ffda74

# blue
color4  #b36670
color12 #d47481

# magenta
color5  #ee8d81
color13 #ff9a8b

#cyan
color6  #ffd362
color14 #ffe853

#white
color7  #EBEBEB
color15 #fef2ec


