background            #040710
foreground            #cfd8e9

# black
color0  #040710
color8  #5b5d63

# red
color1  #749cef
color9  #96bfff

# green
color2  #e47c77
color10 #ff9d97

# yellow
color3  #6ab368
color11 #87dd78

# blue
color4  #4775d8
color12 #6896ff

# magenta
color5  #d15453
color13 #ff7471

#cyan
color6  #309132
color14 #4bbb30

#white
color7  #cfd8e9
color15 #d0e4ff


