background            #06041A
foreground            #F7B377

# black
color0  #06041A
color8  #5d5d63

# red
color1  #be594b
color9  #ed7966

# green
color2  #eb8e57
color10 #ffaf66

# yellow
color3  #ffbf65
color11 #ffc800

# blue
color4  #826ec0
color12 #a88df6

# magenta
color5  #996aa7
color13 #c289d8

#cyan
color6  #8271c3
color14 #a891f9

#white
color7  #F7B377
color15 #ffba51


