# Background and foreground colors
background = #040710
foreground = #cfd8e9

# Standard colors
palette = 0=#040710
palette = 1=#749cef
palette = 2=#e47c77
palette = 3=#6ab368
palette = 4=#4775d8
palette = 5=#d15453
palette = 6=#309132
palette = 7=#cfd8e9

# Bright colors
palette = 8=#5b5d63
palette = 9=#96bfff
palette = 10=#ff9d97
palette = 11=#87dd78
palette = 12=#6896ff
palette = 13=#ff7471
palette = 14=#4bbb30
palette = 15=#d0e4ff
