$color = rgba(4, 7, 16, 1)
$inner_color = rgba(4, 7, 16, 0.66)
$outer_color = rgba(209, 84, 83, 1)
$font_color = rgba(207, 216, 233, 1)
$placeholder_color = rgba(207, 216, 233, 0.7)
$check_color = rgba(48, 145, 50, 1)
