# Background and foreground colors
background = #000407
foreground = #d9e6f5

# Standard colors
palette = 0=#000407
palette = 1=#a7b368
palette = 2=#b6c377
palette = 3=#c9d285
palette = 4=#5ebcdc
palette = 5=#66bee3
palette = 6=#68d5d7
palette = 7=#d9e6f5

# Bright colors
palette = 8=#5e6468
palette = 9=#c8d873
palette = 10=#c0d450
palette = 11=#d5e35f
palette = 12=#76deff
palette = 13=#7dddff
palette = 14=#25e9ed
palette = 15=#cfeeff
