$color = rgba(0, 4, 7, 1)
$inner_color = rgba(0, 4, 7, 0.66)
$outer_color = rgba(102, 190, 227, 1)
$font_color = rgba(217, 230, 245, 1)
$placeholder_color = rgba(217, 230, 245, 0.7)
$check_color = rgba(104, 213, 215, 1)
