background            #000407
foreground            #d9e6f5

# black
color0  #000407
color8  #5e6468

# red
color1  #a7b368
color9  #c8d873

# green
color2  #b6c377
color10 #c0d450

# yellow
color3  #c9d285
color11 #d5e35f

# blue
color4  #5ebcdc
color12 #76deff

# magenta
color5  #66bee3
color13 #7dddff

#cyan
color6  #68d5d7
color14 #25e9ed

#white
color7  #d9e6f5
color15 #cfeeff


