# Vim-style tmux bindings for copy mode
# 'v' begins selection (like Vim's visual mode)
bind-key -T copy-mode-vi v send-keys -X begin-selection

# 'y' yanks (copies) selection to clipboard (like Vim's yank)
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Update Enter key behavior in vim-style mode
unbind-key -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-selection-and-cancel

bind S choose-tree -s
# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Don't allow escape lag
set -sg escape-time 0

#PLUGINS ===============
set -g @plugin 'tmux-plugins/tpm'
# TPM NEEDS TO BE AT TOP
# PUT OTHER PLUGINS DOWN HERE vvvvvv
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
